language: python
python: 3.6
sudo: false
env:
  matrix:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=flake8
install:
- pip install tox
- pip install coveralls
script:
- tox -e $TOX_ENV
after_success:
  coveralls
notifications:
  email: false